# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM starslab/xgo2:1.17.3

LABEL MAINTAINER Péter Szilágyi <peterke@gmail.com>
